<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>A Racialized Electorate: Changing demographic predictors of voting behavior in 1992 and 2016</title>
  <meta name="description" content="A Racialized Electorate: Changing demographic predictors of voting behavior in 1992 and 2016">
  <meta name="generator" content="bookdown 0.5.4 and GitBook 2.6.7">

  <meta property="og:title" content="A Racialized Electorate: Changing demographic predictors of voting behavior in 1992 and 2016" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="A Racialized Electorate: Changing demographic predictors of voting behavior in 1992 and 2016" />
  
  
  

<meta name="author" content="Students in UGA’s Introduction to Spatial Analysis class in Fall 2017">


<meta name="date" content="2017-12-12">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="index.html">
<link rel="next" href="south.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />










</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Background</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#overview"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data"><i class="fa fa-check"></i><b>1.2</b> Data</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#voting"><i class="fa fa-check"></i><b>1.2.1</b> Voting</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#demographics"><i class="fa fa-check"></i><b>1.2.2</b> Demographics</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#analysis"><i class="fa fa-check"></i><b>1.3</b> Analysis</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#references"><i class="fa fa-check"></i><b>1.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="northeast.html"><a href="northeast.html"><i class="fa fa-check"></i><b>2</b> Northeast</a><ul>
<li class="chapter" data-level="2.1" data-path="northeast.html"><a href="northeast.html#overview-1"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="northeast.html"><a href="northeast.html#descriptive-analysis"><i class="fa fa-check"></i><b>2.2</b> Descriptive Analysis</a><ul>
<li class="chapter" data-level="2.2.1" data-path="northeast.html"><a href="northeast.html#percent-not-white-non-hispanic"><i class="fa fa-check"></i><b>2.2.1</b> Percent not White, non-Hispanic</a></li>
<li class="chapter" data-level="2.2.2" data-path="northeast.html"><a href="northeast.html#median-household-income"><i class="fa fa-check"></i><b>2.2.2</b> Median Household Income</a></li>
<li class="chapter" data-level="2.2.3" data-path="northeast.html"><a href="northeast.html#percent-with-a-bachelors-degree"><i class="fa fa-check"></i><b>2.2.3</b> Percent with a Bachelor’s Degree</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="northeast.html"><a href="northeast.html#models"><i class="fa fa-check"></i><b>2.3</b> Models</a><ul>
<li class="chapter" data-level="2.3.1" data-path="northeast.html"><a href="northeast.html#percent-not-white-non-hispanic-1"><i class="fa fa-check"></i><b>2.3.1</b> Percent not White, non-Hispanic</a></li>
<li class="chapter" data-level="2.3.2" data-path="northeast.html"><a href="northeast.html#median-household-income-1"><i class="fa fa-check"></i><b>2.3.2</b> Median Household Income</a></li>
<li class="chapter" data-level="2.3.3" data-path="northeast.html"><a href="northeast.html#percent-with-a-bachelors-degree-1"><i class="fa fa-check"></i><b>2.3.3</b> Percent with a Bachelor’s Degree</a></li>
<li class="chapter" data-level="2.3.4" data-path="northeast.html"><a href="northeast.html#multivariate-models"><i class="fa fa-check"></i><b>2.3.4</b> Multivariate Models</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="northeast.html"><a href="northeast.html#summary"><i class="fa fa-check"></i><b>2.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="south.html"><a href="south.html"><i class="fa fa-check"></i><b>3</b> South</a><ul>
<li class="chapter" data-level="3.1" data-path="south.html"><a href="south.html#overview-2"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="south.html"><a href="south.html#descriptive-analysis-1"><i class="fa fa-check"></i><b>3.2</b> Descriptive analysis</a><ul>
<li class="chapter" data-level="3.2.1" data-path="south.html"><a href="south.html#percent-not-white"><i class="fa fa-check"></i><b>3.2.1</b> Percent not White</a></li>
<li class="chapter" data-level="3.2.2" data-path="south.html"><a href="south.html#median-household-income-2"><i class="fa fa-check"></i><b>3.2.2</b> Median household income</a></li>
<li class="chapter" data-level="3.2.3" data-path="south.html"><a href="south.html#percent-with-a-bachelors-degree-2"><i class="fa fa-check"></i><b>3.2.3</b> Percent with a bachelor’s degree</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="south.html"><a href="south.html#models-1"><i class="fa fa-check"></i><b>3.3</b> Models</a><ul>
<li class="chapter" data-level="3.3.1" data-path="south.html"><a href="south.html#percent-not-white-non-hispanic-2"><i class="fa fa-check"></i><b>3.3.1</b> Percent not White, non-Hispanic</a></li>
<li class="chapter" data-level="3.3.2" data-path="south.html"><a href="south.html#median-household-income-3"><i class="fa fa-check"></i><b>3.3.2</b> Median household income</a></li>
<li class="chapter" data-level="3.3.3" data-path="south.html"><a href="south.html#percent-with-a-bachelors-degree-3"><i class="fa fa-check"></i><b>3.3.3</b> Percent with a bachelor’s degree</a></li>
<li class="chapter" data-level="3.3.4" data-path="south.html"><a href="south.html#multivariate-models-1"><i class="fa fa-check"></i><b>3.3.4</b> Multivariate models</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="south.html"><a href="south.html#summary-1"><i class="fa fa-check"></i><b>3.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="midwest.html"><a href="midwest.html"><i class="fa fa-check"></i><b>4</b> Midwest</a><ul>
<li class="chapter" data-level="4.1" data-path="midwest.html"><a href="midwest.html#overview-3"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="midwest.html"><a href="midwest.html#descriptive-analysis-2"><i class="fa fa-check"></i><b>4.2</b> Descriptive analysis</a><ul>
<li class="chapter" data-level="4.2.1" data-path="midwest.html"><a href="midwest.html#percent-not-white-non-hispanic-3"><i class="fa fa-check"></i><b>4.2.1</b> Percent not White, non-Hispanic</a></li>
<li class="chapter" data-level="4.2.2" data-path="midwest.html"><a href="midwest.html#median-household-income-4"><i class="fa fa-check"></i><b>4.2.2</b> Median household income</a></li>
<li class="chapter" data-level="4.2.3" data-path="midwest.html"><a href="midwest.html#percent-with-a-bachelors-degree-4"><i class="fa fa-check"></i><b>4.2.3</b> Percent with a bachelor’s degree</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="midwest.html"><a href="midwest.html#models-2"><i class="fa fa-check"></i><b>4.3</b> Models</a><ul>
<li class="chapter" data-level="4.3.1" data-path="midwest.html"><a href="midwest.html#percent-not-white-non-hispanic-4"><i class="fa fa-check"></i><b>4.3.1</b> Percent not White, non-Hispanic</a></li>
<li class="chapter" data-level="4.3.2" data-path="midwest.html"><a href="midwest.html#median-household-income-5"><i class="fa fa-check"></i><b>4.3.2</b> Median household income</a></li>
<li class="chapter" data-level="4.3.3" data-path="midwest.html"><a href="midwest.html#percent-with-a-bachelors-degree-5"><i class="fa fa-check"></i><b>4.3.3</b> Percent with a bachelor’s degree</a></li>
<li class="chapter" data-level="4.3.4" data-path="midwest.html"><a href="midwest.html#multivariate-models-2"><i class="fa fa-check"></i><b>4.3.4</b> Multivariate models</a></li>
<li class="chapter" data-level="4.3.5" data-path="midwest.html"><a href="midwest.html#residual-analysis"><i class="fa fa-check"></i><b>4.3.5</b> Residual Analysis</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="midwest.html"><a href="midwest.html#summary-2"><i class="fa fa-check"></i><b>4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="west.html"><a href="west.html"><i class="fa fa-check"></i><b>5</b> West</a><ul>
<li class="chapter" data-level="5.1" data-path="west.html"><a href="west.html#overview-4"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="west.html"><a href="west.html#descriptive-analysis-3"><i class="fa fa-check"></i><b>5.2</b> Descriptive analysis</a><ul>
<li class="chapter" data-level="5.2.1" data-path="west.html"><a href="west.html#percent-not-white-non-hispanic-5"><i class="fa fa-check"></i><b>5.2.1</b> Percent not White, non-Hispanic</a></li>
<li class="chapter" data-level="5.2.2" data-path="west.html"><a href="west.html#median-household-income-6"><i class="fa fa-check"></i><b>5.2.2</b> Median household income</a></li>
<li class="chapter" data-level="5.2.3" data-path="west.html"><a href="west.html#percent-with-a-bachelors-degree-6"><i class="fa fa-check"></i><b>5.2.3</b> Percent with a bachelor’s degree</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="west.html"><a href="west.html#models-3"><i class="fa fa-check"></i><b>5.3</b> Models</a><ul>
<li class="chapter" data-level="5.3.1" data-path="west.html"><a href="west.html#percent-not-white-non-hispanic-6"><i class="fa fa-check"></i><b>5.3.1</b> Percent not White, non-Hispanic</a></li>
<li class="chapter" data-level="5.3.2" data-path="west.html"><a href="west.html#median-household-income-7"><i class="fa fa-check"></i><b>5.3.2</b> Median household income</a></li>
<li class="chapter" data-level="5.3.3" data-path="west.html"><a href="west.html#percent-with-a-bachelors-degree-7"><i class="fa fa-check"></i><b>5.3.3</b> Percent with a bachelor’s degree</a></li>
<li class="chapter" data-level="5.3.4" data-path="west.html"><a href="west.html#multivariate-models-3"><i class="fa fa-check"></i><b>5.3.4</b> Multivariate models</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="west.html"><a href="west.html#summary-3"><i class="fa fa-check"></i><b>5.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="concluding-thoughts.html"><a href="concluding-thoughts.html"><i class="fa fa-check"></i><b>6</b> Concluding thoughts</a><ul>
<li class="chapter" data-level="6.1" data-path="concluding-thoughts.html"><a href="concluding-thoughts.html#trends-in-regional-models"><i class="fa fa-check"></i><b>6.1</b> Trends in regional models</a><ul>
<li class="chapter" data-level="6.1.1" data-path="concluding-thoughts.html"><a href="concluding-thoughts.html#comparison-to-national-models"><i class="fa fa-check"></i><b>6.1.1</b> Comparison to national models</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="concluding-thoughts.html"><a href="concluding-thoughts.html#limitations"><i class="fa fa-check"></i><b>6.2</b> Limitations</a></li>
<li class="chapter" data-level="6.3" data-path="concluding-thoughts.html"><a href="concluding-thoughts.html#final-thoughts"><i class="fa fa-check"></i><b>6.3</b> Final thoughts</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Racialized Electorate: Changing demographic predictors of voting behavior in 1992 and 2016</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="northeast" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Northeast</h1>
<div id="overview-1" class="section level2">
<h2><span class="header-section-number">2.1</span> Overview</h2>
<p>The Northeast region of the United States includes Connecticut, Maine, Massachusetts, New Hampshire, New Jersey, New York, Pennsylvania, Rhode Island, and Vermont. The number of congressional seats for these states ranged from 1 to 31 in 1990 with New York having the highest and Vermont the lowest. In 2015, the range of congressional seats decreased to 1 to 27. Five states lost congressional seats from 1990 to 2015. The partisan landscape for the northeastern U.S. has largely leaned Democratic. Of these states, only Connecticut, New Jersey, Pennsylvania, and Vermont had higher percentages of Republican voters in 1990. While in 2015, only Connecticut and New Jersey were dominated by Republican voters.</p>
</div>
<div id="descriptive-analysis" class="section level2">
<h2><span class="header-section-number">2.2</span> Descriptive Analysis</h2>
<div id="percent-not-white-non-hispanic" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Percent not White, non-Hispanic</h3>
<p><img src="sample_book_files/figure-html/2-1.png" width="672" /></p>
<p><img src="sample_book_files/figure-html/4-1.png" width="672" /></p>
<p><img src="sample_book_files/figure-html/5-1.png" width="672" /><img src="sample_book_files/figure-html/5-2.png" width="672" /></p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.8084  3.0713  6.0933 16.5257 12.7728 98.3121</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   3.458   9.881  21.183  28.760  30.178  98.761</code></pre>
<p>In congressional districts in the Northeast Region, percent non-white population has been significantly increased between 1990 and 2015, although most values exhibits values lower than 40%.</p>
<p>First, significant increases in the percent non-white population were identified from mean and median values for last 15 years. By simply comparing the values, % of non-white population were positively distributed in both 1990 and 2015. However, the highest peaks were shifted to the higher values from 1990 to 2015; mean values were shifted from 16.53 to 28.76 and median values were 6.10 to 21.18.</p>
<p>From histogram analysis, we can analyze where these shifts are attributed. We can find the kurtosis has been significantly changed between 1990 and 2015. In 1990, about 60% of districts in this region exhibited less than 10% of non-white population, but in 2015, values were shifted to higher range and the highest peak was diminished by more than half. In other words, the percent non-white population in both 1990 and 2015 follow Poisson distributions of low lambda values. However, the intensity between 0-10% in 1990 has been decreased and the peak were shifted and alleviated to 0-30% range in 2015.</p>
<p>Specifically, all of districts in the northeastern states exhibit similar trends to regional analysis, experiencing significant increase in percent non-white population. Among them, districts in New Jersey experienced the highest increase in percent non-white population with 37.69%, followed by New York with 29.06%. Meanwhile, districts in Maine, New Hampshire, and Vermont did not changed much in the percent of non-white population, with small increase around 3 or 4 percent.</p>
<p>Ridge plots of 1990 and 2015 reveal additional information that changes in higher ranges played significant role in increased mean and median values as well as supporting the abovementioned trends. In 2015, several districts in New York and New Jersey transformed into non-white population dominant districts with more than 70 or 80%. Likewise, Connecticut and Maine in 2015 have some districts with more than 40% of non-white population which did not exist in 1990.</p>
</div>
<div id="median-household-income" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Median Household Income</h3>
<p><img src="sample_book_files/figure-html/6-1.png" width="672" /></p>
<p><img src="sample_book_files/figure-html/8-1.png" width="672" /></p>
<pre><code>## 
## &lt;table style=&quot;text-align:center&quot;&gt;&lt;caption&gt;&lt;strong&gt;1990 Medium Household Income Summary Stats&lt;/strong&gt;&lt;/caption&gt;
## &lt;tr&gt;&lt;td colspan=&quot;7&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Statistic&lt;/td&gt;&lt;td&gt;N&lt;/td&gt;&lt;td&gt;Mean&lt;/td&gt;&lt;td&gt;Median&lt;/td&gt;&lt;td&gt;Min&lt;/td&gt;&lt;td&gt;Max&lt;/td&gt;&lt;td&gt;St. Dev.&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td colspan=&quot;7&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;districts_1990.medhhinc&lt;/td&gt;&lt;td&gt;88&lt;/td&gt;&lt;td&gt;62,504.840&lt;/td&gt;&lt;td&gt;58,867.500&lt;/td&gt;&lt;td&gt;25,937.060&lt;/td&gt;&lt;td&gt;107,859.200&lt;/td&gt;&lt;td&gt;17,357.080&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td colspan=&quot;7&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;</code></pre>
<p><img src="sample_book_files/figure-html/9-1.png" width="672" /><img src="sample_book_files/figure-html/9-2.png" width="672" /></p>
<pre><code>## 
## &lt;table style=&quot;text-align:center&quot;&gt;&lt;caption&gt;&lt;strong&gt;2015 Medium Household Income Summary Stats&lt;/strong&gt;&lt;/caption&gt;
## &lt;tr&gt;&lt;td colspan=&quot;7&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Statistic&lt;/td&gt;&lt;td&gt;N&lt;/td&gt;&lt;td&gt;Mean&lt;/td&gt;&lt;td&gt;Median&lt;/td&gt;&lt;td&gt;Min&lt;/td&gt;&lt;td&gt;Max&lt;/td&gt;&lt;td&gt;St. Dev.&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td colspan=&quot;7&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;districts_2015.medhhinc&lt;/td&gt;&lt;td&gt;78&lt;/td&gt;&lt;td&gt;63,251.250&lt;/td&gt;&lt;td&gt;61,136.500&lt;/td&gt;&lt;td&gt;25,100.000&lt;/td&gt;&lt;td&gt;106,917.000&lt;/td&gt;&lt;td&gt;17,544.940&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td colspan=&quot;7&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;</code></pre>
<p><img src="sample_book_files/figure-html/9-3.png" width="672" /><img src="sample_book_files/figure-html/9-4.png" width="672" /></p>
<p>The median income for congressional districts in the northeastern United States have not exhibited much change in overall magnitude and range between 1990 and 2015. The range of median income for 1990 was $25,937 to $107,859 while the range for 2015 was $25,100 to $106,917. Median income across the districts for 1990 was positively skewed which could be inferred through the comparison of the mean and median values, $65,505 and $58,867 respectively. This was confirmed in the histogram plot of median income frequency with a right-side tail and in the Q-Q plot with a tail deviating from the Q-Q line at the bottom left of the graph.</p>
<p>Median income across the districts for 2015 appeared somewhat more normally distributed. The mean and median were very similar, $63,251 and $61,136 respectively. However, plotting the Q-Q plot still showed some skewness in the positive direction. Likewise, in the histogram plot of median income frequency, there appeared to be more districts exhibiting median income in the $40,000 to $70,000 range; a shift toward the right from 1990. It appears that median income levels were increasing slightly. There was an increase in the number of districts with median income in the $60,000 to $70,000 range and a decrease in the $30,000 to $40,000 range. These changes were subtle and could be explained in some part to the variation in sample size between the two years: 1990 with 88 districts and 2015 with 78 districts.</p>
<p>Using the ridge plots, comparisons could be made of median income at the state level. Similar trends seen at the region level were seen for individual states. States in 2015 exhibited broader platykurtic peaks in median income with less pronounced multimodality. For example, New Jersey in 1990 showed three strong peaks in median income at approximately $50,000, $70,000, and $85,000 where in 2015 they had flattened out. Another example, Connecticut, in 1990, exhibited strong leptokurtic kurtosis but by 2015 and had a more mesokurtic form.</p>
<p>Median income mapped at the district level showed more clearly the spatial changes that occurred between 1990 and 2015. In 2015, more districts fell in the $50,000 to $75,000 class which reflected the increase in median income seen in the previous statistical graphics and measurements. New York districts, in 1990, were predominantly classified as $25,000 to $50,000 while, in 2015, the state became more than fifty percent classified as $50,000 to $75,000. Another interesting trend was seen in Connecticut where a migration of higher income moved east, away from New York City. Similarly, there is a shift of higher income moving away from New York City in New Jersey to the southwest.</p>
</div>
<div id="percent-with-a-bachelors-degree" class="section level3">
<h3><span class="header-section-number">2.2.3</span> Percent with a Bachelor’s Degree</h3>
<p><img src="sample_book_files/figure-html/10-1.png" width="672" /></p>
<p><img src="sample_book_files/figure-html/12-1.png" width="672" /></p>
<p>The ridge plots demonstrate that there is a shift in the mean to higher percentages from 1990 to 2015 in the Northeast Region. The overall range of the ridge plots from 1990 to 2015 shift to larger percentages with the 2015 plots having districts with as high as 75% of the population having a BA degree or higher. The ridge plots for New York, New Jersey, and Pennsylvania have a similar shape with a main peak in lower percentages, but a few smaller peaks in higher percentages. Comparing CT’s ridge plots from 1990 to 2015, the pattern of the curve stays the same however, there is a shift in the values towards higher percentages. New York has the largest range in percentages with some districts having almost 0% of the people with BA degrees or higher to 75% of the people having BA degrees or higher.</p>
<p>The spatial distribution map shows a similar pattern to the ridge plots, overall there is an increase in the percentage of people who have a Bachelor’s degree from 1990 to 2015, however in southwestern PA there appears to be no change to the percentage of people with a Bachelor’s degree. The largest percentages of people with a BA degree in 2015 are located in Northern New Jersey, southeastern New York, southern Connecticut, and eastern Massachusetts.</p>
</div>
</div>
<div id="models" class="section level2">
<h2><span class="header-section-number">2.3</span> Models</h2>
<div id="percent-not-white-non-hispanic-1" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Percent not White, non-Hispanic</h3>
<table style="text-align:center">
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
Model results
</td>
</tr>
<tr>
<td>
</td>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
Pct. voting democratic
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
1992
</td>
<td>
2016
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
nonwht_pct
</td>
<td>
0.264<sup>***</sup>
</td>
<td>
0.432<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.058)
</td>
<td>
(0.050)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
42.781<sup>***</sup>
</td>
<td>
42.185<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1.792)
</td>
<td>
(1.930)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
88
</td>
<td>
78
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.195
</td>
<td>
0.500
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.186
</td>
<td>
0.493
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
14.220 (df = 86)
</td>
<td>
11.486 (df = 76)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
20.880<sup>***</sup> (df = 1; 86)
</td>
<td>
75.900<sup>***</sup> (df = 1; 76)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="2" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
<p><img src="sample_book_files/figure-html/15-1.png" width="672" /></p>
<p>Linear regression model is applied to identify how the percent non-white population is related to the percent voting democrat. According to the results, linear regression results follow heteroskedasticity in plotting two variables, more significantly for the result of 1990. Since districts with low percent non-white populations show extremely wide-ranging percent voting democrat, it is hard to draw meaningful analysis from this range due to the residuals. In addition, more than half of districts in Northeast region are of the low percent non-white population which lead to deteriorate the power of model (e.g. R-squared value).</p>
<p>Despite these weaknesses, the percent non-white population in congressional districts tend to exhibit positive relation to percent voting democrat overall; as 1% of non-white population increases, the percent of people who vote Democrat increases by .26% in 1990 and .43% in 2015. P-values for both regression results were less than 0.01 that explain high significance of the results. Adjusted R-squared values, which refer to the explanation power, are estimated as .186 for 1990 and .493 for 2015 indicating that 18.6% and 49.3% of data are explained by linear regression model.</p>
<p>One noticeable point from the linear regression models is that the result for 2015 is highly improved than 1990. The reason behind the improvement can be attributed to the shift of the percent non-white population. When we see scatter plots from two models, the most noteworthy difference is that the points ranged from 0 to 10% in x-axis and 0 to 80% in y-axis in 1990 shifted to 0-30% in x-axis and 25-70% in y-axis in 2015. The change in distribution resulted in reduced residuals of linear regression and increased model significance.</p>
</div>
<div id="median-household-income-1" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Median Household Income</h3>
<table style="text-align:center">
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
Model results
</td>
</tr>
<tr>
<td>
</td>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
Pct. voting democratic
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
1992
</td>
<td>
2016
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
medhhinc
</td>
<td>
-0.0003<sup>***</sup>
</td>
<td>
-0.0001
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.0001)
</td>
<td>
(0.0001)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
65.881<sup>***</sup>
</td>
<td>
63.848<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(5.994)
</td>
<td>
(6.832)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
88
</td>
<td>
78
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.109
</td>
<td>
0.025
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.099
</td>
<td>
0.012
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
14.964 (df = 86)
</td>
<td>
16.031 (df = 76)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
10.513<sup>***</sup> (df = 1; 86)
</td>
<td>
1.970 (df = 1; 76)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="2" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
<p><img src="sample_book_files/figure-html/18-1.png" width="672" /></p>
<p>Linear regression was used to model percent voting democrat based on median income at the congressional district level for states in the northeast. Two linear models were made, one for 1990 and one for 2015. Both models appeared to show little correlation in median income and percent voting democrat. The model for 1990 had an R2 value of 0.109, meaning median income described 10.9% of the variation seen in percent voting democrat across districts. The 2015 model received an R2 of 0.025, describing even less variation than the 1990 model. The direction of both coefficients suggested that there was a negative correlation between median income and percent voting democrat. However, only the coefficient for the 1990 model showed significance at the 0.05 level. The 2016 model coefficient received a p-value of 0.164.</p>
</div>
<div id="percent-with-a-bachelors-degree-1" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Percent with a Bachelor’s Degree</h3>
<table style="text-align:center">
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
Model results
</td>
</tr>
<tr>
<td>
</td>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
Pct. voting democratic
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
1992
</td>
<td>
2016
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
badeg_pct
</td>
<td>
-0.483<sup>**</sup>
</td>
<td>
0.193
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.206)
</td>
<td>
(0.167)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
56.286<sup>***</sup>
</td>
<td>
48.614<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(4.217)
</td>
<td>
(5.491)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
88
</td>
<td>
78
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.060
</td>
<td>
0.017
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.049
</td>
<td>
0.004
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
15.366 (df = 86)
</td>
<td>
16.097 (df = 76)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
5.530<sup>**</sup> (df = 1; 86)
</td>
<td>
1.337 (df = 1; 76)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="2" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
<p><img src="sample_book_files/figure-html/21-1.png" width="672" /></p>
<p>The model output for 1992 displays that for every percent increase in people with a Bachelor’s degree the percent of people who vote democratic decreases by .483, this value is fairly large in magnitude with an approximate .5% decrease for every increase in BA degree. This value is statistically significant based on the p value. When examining the power of the the adjusted R2 value is very low indicating that the regression line does not fit well with the data. In addition, The F statistic is significant indicating the ability to reject the null hypothesis, so this model is better than one with only the intercept. The scatterplot for the 1992 model, shows a slight decrease in democratic voting percentage as BA degree percentage increases, it appears there is a possible high outlier on this plot. Although the model output indicates that the regression line is not a good fit for the data, the scatter plot’s regression line divides the data well as to display a normal distribution of the residuals.</p>
<p>There is a shift when analyzing the results for the 2016 model output. For every percent increase in people with a Bachelor’s degree, the percentage of voting democratic increased by .193, this value is not as large as the 1992 model and is also not statistically significant. When examining the power of the 2016 model, the adjusted R2 is even lower than the 1992 model, so this regression line does not fit the data well. The F Statistic is not statistically significant, so the null hypothesis cannot be rejected indicating that this model is no better than a model with just the intercept. Although the scatter plot displays the regression line that shows a slight increase in percentage democratic vote as percentage BA degree increases, there does not appear to be a clear linear pattern in the data as well as quite a few outliers.</p>
</div>
<div id="multivariate-models" class="section level3">
<h3><span class="header-section-number">2.3.4</span> Multivariate Models</h3>
<table style="text-align:center">
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
Model results
</td>
</tr>
<tr>
<td>
</td>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
Pct. voting democratic
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
1992
</td>
<td>
2016
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
nonwht_pct
</td>
<td>
0.225<sup>***</sup>
</td>
<td>
0.401<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.060)
</td>
<td>
(0.047)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
medhhinc
</td>
<td>
-0.0002
</td>
<td>
-0.0004<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.0001)
</td>
<td>
(0.0001)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
badeg_pct
</td>
<td>
0.087
</td>
<td>
0.747<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.291)
</td>
<td>
(0.179)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
55.602<sup>***</sup>
</td>
<td>
43.293<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(6.332)
</td>
<td>
(5.092)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
88
</td>
<td>
78
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.236
</td>
<td>
0.595
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.209
</td>
<td>
0.578
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
14.022 (df = 84)
</td>
<td>
10.478 (df = 74)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
8.641<sup>***</sup> (df = 3; 84)
</td>
<td>
36.179<sup>***</sup> (df = 3; 74)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="2" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
<pre><code>## nonwht_pct   medhhinc  badeg_pct 
##   1.117154   2.475413   2.406476</code></pre>
<pre><code>## nonwht_pct   medhhinc  badeg_pct 
##   1.091564   2.865457   2.721901</code></pre>
<pre><code>##             badeg_pct medhhinc nonwht_pct pct_dem_adj
## badeg_pct        1.00     0.76      -0.28       -0.25
## medhhinc         0.76     1.00      -0.32       -0.33
## nonwht_pct      -0.28    -0.32       1.00        0.44
## pct_dem_adj     -0.25    -0.33       0.44        1.00
## 
## n= 88 
## 
## 
## P
##             badeg_pct medhhinc nonwht_pct pct_dem_adj
## badeg_pct             0.0000   0.0090     0.0210     
## medhhinc    0.0000             0.0024     0.0017     
## nonwht_pct  0.0090    0.0024              0.0000     
## pct_dem_adj 0.0210    0.0017   0.0000</code></pre>
<pre><code>##             badeg_pct medhhinc nonwht_pct pct_dem_adj
## badeg_pct        1.00     0.79      -0.09        0.13
## medhhinc         0.79     1.00      -0.24       -0.16
## nonwht_pct      -0.09    -0.24       1.00        0.71
## pct_dem_adj      0.13    -0.16       0.71        1.00
## 
## n= 78 
## 
## 
## P
##             badeg_pct medhhinc nonwht_pct pct_dem_adj
## badeg_pct             0.0000   0.4287     0.2512     
## medhhinc    0.0000             0.0338     0.1645     
## nonwht_pct  0.4287    0.0338              0.0000     
## pct_dem_adj 0.2512    0.1645   0.0000</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  multimodel1990
## BP = 11.146, df = 3, p-value = 0.01096</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  multimodel2015
## BP = 0.72458, df = 3, p-value = 0.8674</code></pre>
<p><img src="sample_book_files/figure-html/24-1.png" width="672" /><img src="sample_book_files/figure-html/24-2.png" width="672" /></p>
<p>When comparing the 1992 multivariate model to the individual models, all of the models are statistically significant based on the F Statistic indicating that these models are better than a model made of only the intercept. Overall, the multivariate model fits the data better than the individual models as indicated by the larger adjusted R2 value. Although, the multivariate model is better than the individual models, two of the three variables coefficients (median household income and percent with BA degree) are not statistically significant. Both the percent BA degree and the non-white percent coefficients result in an increase in the percent voting democratic. Based on the results of the VIF, multicollinearity is not an issue because all of the values are less the 5 referring that three variables are independent each other. In addition, heteroskedasticity is an issue based on the statistically significant results of the BP test, so the null hypothesis that the data is not heteroskedastic can be rejected. The density plots of the residuals indicate that the data is approximately normally distributed, which is important because when this assumption is met the results of the model can be trusted more accurately. Examining the spatial distribution of the residuals, the model overestimated the percent democratic vote in most of New York and Vermont, as well as some districts in northwestern PA, northern NJ, and western CT. The model underestimated the democratic voting percentage in districts in southwestern PA, most of Rhode Island, eastern MA, most of NH, and southern ME.</p>
<p>The 2016 multivariate model results indicate that this model is more powerful not only than a model made up of only the intercept based on the results of the F test as well as more powerful than the univariate models. In addition, the multivariate model fits the data much better than the 2016 univariate models and the 1992 multivariate model based on the larger adjusted R2 value. Unlike the 1992 multivariate model, all of the coefficients of the 2016 model are statistically significant. As with the 1992 results, an increase in both the non-white percent variable and the BA degree percent result in an increase in the percent voting democratic. Similar to the 1992 results, multicollinearity is not an issue in this case due to the VIF values being lower than 5. Unlike the 1992 results, heteroskedasticity is not an issue because the p value is not statistically significant based on the BP test, so the null hypothesis that the data is not heteroskedastic cannot be rejected. Based on the density plots, it appears that the residuals are normally distributed, which meets the assumption necessary for trusting the results of the models. Examining the residuals spatial distribution, the model overestimates the voting percentage in northern and central NJ, much of NY, while the largest areas of underestimates are located in VT, MA, eastern CT, and RI.</p>
</div>
</div>
<div id="summary" class="section level2">
<h2><span class="header-section-number">2.4</span> Summary</h2>
<p>The multivariate model was a stronger predictor of democratic voting than individual univariate models. The variables in the 2016 model explain more of the variation seen percent democratic voting than in 1992.</p>
<p>Race and education level appear to be defining party lines more through time in the Northeast. There have been changes in the geographic distribution of these variables. In 1992, the Northeast region was predominantly white. As time goes on, the non-white percent population increases and spreads, emanating from population centers, i.e. New York City. The demographic distribution has had a greater influence on the percent voting democratic.</p>
<p>The variables percent non-white and median household income both doubled in strength between 1992 and 2016, though their directions are opposite. The percent BA degree or higher became significant and an influential factor in predicting democratic voting through time.</p>
<p>Based on our results, the voting patterns of 2016 in the Northeast were more influenced by the variables studied here than 1992. The models indicate that other variables may have affected the voting patterns in 1992, therefore it could be beneficial to include different contributors to better understand the democratic vote in 1992.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="south.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
